### ISSUE TITLE
Annotation prefix is not removed

### ISSUE THREAD

**Issue by ivanayov** [openfaas/faas-swarm#29]
This is the function configuration:
```
provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  kafka-test:
    lang: python
    handler: ./kafka-test
    image: kafka-test
    annotations:
      topic: faas-request
    basic_auth: false
```
`curl -X GET http://127.0.0.1:8080/system/function/kafka-test` should return
```
{  
   "name":"kafka-test",
   "image":"kafka-test:latest",
   "invocationCount":0,
   "replicas":1,
   "envProcess":"python index.py",
   "availableReplicas":1,
   "labels":{  
      "com.openfaas.function":"kafka-test",
      "com.openfaas.uid":"92309200",
      "function":"true"
   },
   "annotations":{  
      "topic":"faas-request"
   }
}
```
but instead the annotations are prefixed:
```
 "annotations":{  
      "com.openfaas.annotations.topic":"faas-request"
   }
```

## Possible Solution
The bug is on [reader.go#L95](https://github.com/openfaas/faas-swarm/blob/master/handlers/reader.go#L95).
The prefix is not removed.

## Context

Found while testing pull [#6](https://github.com/openfaas-incubator/kafka-connector/pull/6)
Follows #28 

Some integration tests are good to have.

@ewilde  Could you please have a look?
