### ISSUE TITLE
How to connect to TLS socket?

### ISSUE THREAD

**Issue by kinghuang** [openfaas/faas-swarm#51]
## Expected Behaviour

Be able to connect to a Docker API endpoint with TLS enabled.

## Current Behaviour

I have a openfaas/faas-swarm service with the following environment variables set.

```
DOCKER_API_VERSION: 1.39
DOCKER_HOST: tcp://10.57.21.68:2376
DOCKER_TLS: 1
```

I'm expecting faas-swarm to connect to the Docker API endpoint with TLS enabled. But, the logs show it's not.

```
2019/06/26 17:35:46 Error with Docker server: Get http://10.57.21.68:2376/v1.39/version: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02".
* Are you trying to connect to a TLS-enabled daemon without TLS?
```

## Possible Solution

Unknown.

## Steps to Reproduce (for bugs)

Here's a snippet of my service definition for faas-swarm.

```
  faas-swarm:
    image: openfaas/faas-swarm:0.6.2
    environment:
      read_timeout: 5m
      write_timeout: 5m
      basic_auth: "true"
      secret_mount_path: /run/secrets
      DOCKER_API_VERSION: 1.39
      DOCKER_HOST: tcp://10.57.21.68:2376
      DOCKER_TLS: 1
```

## Context

I want to be able to connect to a remote Docker swarm manager endpoint that has TLS enabled.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): N/A

* Docker version `docker version` (e.g. Docker 17.0.05 ): 18.09.6

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Swarm

* Operating System and version (e.g. Linux, Windows, MacOS): Linux

* Link to your project or a code example to reproduce issue: N/A
