### ISSUE TITLE
The CPU limit/reservation feature does not work in the swarm cluster.

### ISSUE THREAD

**Issue by mangobowl** [openfaas/faas-swarm#58]
The CPU limit/reservation feature described in the [docs](https://docs.openfaas.com/reference/yaml/#function-memorycpu-limits) does not work in the swarm cluster.
the test yml file as following:

**python.yml**
```
version: 1.0
provider:
  name: openfaas
  gateway: http://harbor.my-domain.com:8080
functions:
  python:
    lang: python3-flask
    handler: ./python
    image: harbor.my-domain.com/openfaas-custom/python:latest
    limits:
      cpu: 1000m
      memory: 1024m
    requests:
      cpu: 100m
      memory: 256m
```  

## Current Behaviour

when using `faas-cli deploy -f ./python.yml` deploy this function, the `faas-swarm` service shows some error logs as following:
```
2019/10/18 02:21:08 Error parsing cpu limit: *strconv.NumError
2019/10/18 02:21:08 Error parsing cpu reservations: *strconv.NumError
```

using `docker service inspcet python` to check:

```
...
"Resources": {
                    "Limits": {
                        "MemoryBytes": 1073741824
                    },
                    "Reservations": {
                        "MemoryBytes": 268435456
                    }
                },
...
```

It shows that CPU limit/reservation does not work.

## Expected Behaviour

using `faas-cli up` or `faas-cli deploy` deploy the function should set the CPU limit/reservation correctly.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

CLI:
 commit:  5ff1504047756f9ff2e0a10ae64803ab63df470a
 version: 0.9.3

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.17.3
 sha:     d322f109a8379d19b639c003846e721a24ce9dc0
 commit:  Fix logo location

Provider
 name:          faas-swarm
 orchestration: swarm
 version:       0.7.2
 sha:           ef7d9132e29edc8ff3962685ba772ad6e3f01bda
* Docker version `docker version` (e.g. Docker 17.0.05 ):

docker-ce 18.09
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

Swarm
* Operating System and version (e.g. Linux, Windows, MacOS):

Ubuntu Server 16.04.6
* Link to your project or a code example to reproduce issue:
